import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 52 : 32,
  },
  screen: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  heroTitle: {
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 48,
    marginBottom: 16,
  },
  heroSubtitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
  },
  bottomSection: {
    paddingTop: 16,
    gap: 12,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#000000',
    letterSpacing: 0.2,
  },
  stepPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
  },
  stepPillText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  devBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  devLabel: {
    fontSize: 11,
    fontWeight: '600',
    marginRight: 2,
  },
  devToggle: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  devToggleText: {
    fontSize: 11,
    fontWeight: '700',
  },
  progressTrack: {
    height: 3,
    borderRadius: 2,
    marginBottom: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: 3,
    borderRadius: 2,
  },
  goalBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  goalBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    flexShrink: 1,
  },
  decodeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingTop: 8,
    paddingBottom: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decodeScroll: {
    paddingBottom: 80,
    paddingTop: 8,
  },
  decodeQuestion: {
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -0.5,
    lineHeight: 36,
    marginBottom: 8,
  },
  decodeSub: {
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 22,
    marginBottom: 24,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
  },
  chipText: {
    fontSize: 14,
    fontWeight: '700',
  },
  customRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
  },
  customInlineInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    minHeight: 44,
  },
  customConfirmBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customCancelBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  customCancelText: {
    fontSize: 13,
    fontWeight: '600',
  },
  inheritedTargetCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 14,
    borderWidth: 1.5,
    padding: 16,
    marginBottom: 28,
    gap: 8,
  },
  inheritedLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  inheritedValue: {
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 28,
  },
  editAffordance: {
    padding: 4,
    marginTop: 2,
  },
  helperHint: {
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 19,
    marginTop: 8,
  },
  revealBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 14,
    marginTop: 28,
  },
  revealBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#000',
  },
  revealCard: {
    borderRadius: 20,
    borderWidth: 2,
    padding: 24,
    marginTop: 24,
    alignItems: 'center',
    gap: 8,
    overflow: 'hidden',
  },
  revealLabel: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  revealNumber: {
    fontWeight: '900',
    letterSpacing: -2,
  },
  revealUnit: {
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  mathBox: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 14,
    gap: 4,
    width: '100%',
    marginTop: 8,
  },
  mathLine: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
  },
  lockBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 14,
    marginTop: 4,
    width: '100%',
  },
  lockBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#000',
  },
  startingInput: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    minHeight: 64,
  },
  seedNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 12,
  },
  seedNoticeText: {
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  anchorWhatCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    marginBottom: 4,
    gap: 8,
  },
  anchorWhatText: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 24,
    flex: 1,
  },
  anchorEditInput: {
    fontSize: 17,
    fontWeight: '700',
  },
  whenField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 14,
    borderWidth: 1.5,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  whenFieldText: {
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  calendarHint: {
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 4,
    paddingLeft: 4,
  },
  whereInput: {
    fontSize: 15,
    fontWeight: '600',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    minHeight: 48,
  },
  systemPreview: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    marginTop: 20,
  },
  systemPreviewText: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 24,
  },
  lockedCard: {
    borderRadius: 24,
    borderWidth: 2,
    padding: 32,
    alignItems: 'center',
    gap: 12,
    overflow: 'hidden',
    width: '100%',
  },
  lockedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
  },
  lockedBadgeText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#000',
  },
  lockedGoalLabel: {
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 20,
  },
  lockedInput: {
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 28,
  },
  lockedNextHint: {
    fontSize: 13,
    fontWeight: '500',
    marginTop: 4,
  },
  pathCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    padding: 20,
    gap: 12,
  },
  pathCardLabel: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 3,
  },
  pathCardSub: {
    fontSize: 13,
    fontWeight: '500',
  },
  summaryContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 60,
  },
  summaryCard: {
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 20,
    marginBottom: 14,
    gap: 6,
    overflow: 'hidden',
  },
  summaryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  summaryCardGoalLabel: {
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  summaryCardInput: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 26,
  },
  summaryCardWhen: {
    fontSize: 13,
    fontWeight: '500',
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 8,
  },
  resetBtnText: {
    fontSize: 14,
    fontWeight: '600',
  },
  standardsSkipBtn: {
    alignSelf: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginTop: 20,
  },
  standardsSkipText: {
    fontSize: 13,
    fontWeight: '500',
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  lockedHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  lockedInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    paddingTop: 10,
    marginTop: 4,
  },
  standardTag: {
    borderWidth: 1.5,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  standardTagText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  addAnotherBtn: {
    marginTop: 16,
    width: '100%',
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  addAnotherText: {
    fontSize: 14,
    fontWeight: '700',
  },
  summaryInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  summaryStandardTag: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  summaryAdditionalRow: {
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 10,
    gap: 2,
  },
  stackSectionHeader: {
    borderBottomWidth: 1,
    paddingBottom: 10,
    marginBottom: 4,
  },
  stackSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  stackSectionSub: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  stackTile: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
  },
  stackCheckCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    marginTop: 2,
    flexShrink: 0,
  },
  stackTileInput: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  stackTileWhen: {
    fontSize: 13,
    fontWeight: '500',
  },
  stackGoalTag: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    marginTop: 4,
  },
  stackGoalTagText: {
    fontSize: 11,
    fontWeight: '600',
  },

  // Identity screen
  identityFrame: {
    borderWidth: 2,
    borderRadius: 16,
    padding: 20,
    gap: 0,
  },
  identityTileCard: {
    borderWidth: 1.5,
    borderRadius: 18,
    padding: 20,
    overflow: 'hidden',
  },
  identityTileRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  identityLineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: 14,
  },
  identityLine: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
    flex: 1,
  },
  identityDivider: {
    height: 1,
  },
  identityEditInput: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    minHeight: 80,
  },
  identityEditSave: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  identityEditSaveText: {
    fontSize: 14,
    fontWeight: '700',
  },
  identityEditCancel: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
  },
  identityEditCancelText: {
    fontSize: 14,
    fontWeight: '600',
  },

  // Finale screen
  finaleHeadline: {
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: -0.5,
    lineHeight: 42,
    marginBottom: 32,
  },
  finaleSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  compassCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    gap: 10,
  },
  compassPlaceholder: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  compassSub: {
    fontSize: 13,
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 20,
  },
  finaleStackTile: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    borderWidth: 2,
  },
  finaleStackText: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    marginBottom: 4,
  },
  finaleStackWhen: {
    fontSize: 13,
    fontWeight: '500',
  },
  finaleCheckOuter: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finaleCheckInner: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
  },

  // Signature commit screen
  sigLabel: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  sigPad: {
    height: 180,
    borderRadius: 16,
    borderWidth: 2,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sigHint: {
    fontSize: 14,
    color: '#555',
    fontStyle: 'italic',
  },
  sigClear: {
    position: 'absolute',
    bottom: 10,
    right: 14,
  },
  sigClearText: {
    fontSize: 13,
    fontWeight: '600',
  },
  commitChecklistCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 10,
  },
  commitChecklistRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 10,
    paddingTop: 0,
  },
  commitCheckCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexShrink: 0,
    marginTop: 1,
  },
  commitChecklistText: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    flex: 1,
  },
  commitCheckWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commitDoneTitle: {
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  commitDoneSub: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
  },
  paywallCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    gap: 8,
    width: '100%',
    marginTop: 8,
  },
  paywallLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  paywallSub: {
    fontSize: 14,
    fontStyle: 'italic',
  },

  // Shared primary button (used across new screens)
  primaryBtn: {
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#000',
    letterSpacing: 0.2,
  },

  // Front-half screens
  goalsEntryInput: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    minHeight: 110,
  },
  doneLooksInput: {
    borderWidth: 1.5,
    borderRadius: 14,
    padding: 16,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 26,
    minHeight: 100,
  },
  prefillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
  },
  prefillBtnText: {
    fontSize: 12,
    fontWeight: '600',
  },
  classifyGoalPill: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  classifyGoalText: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 24,
  },
  finishLineCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    gap: 6,
  },
  finishLineLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  finishLineText: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
  },
  fuelSecondaryBtn: {
    alignSelf: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
  },
  fuelSecondaryText: {
    fontSize: 15,
    fontWeight: '600',
  },
  fuelRedirectCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 20,
    gap: 6,
  },
  fuelRedirectIf: {
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  fuelRedirectAction: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
  },
  doneLooksEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  doneLooksHint: {
    fontSize: 13,
    fontWeight: '500',
    fontStyle: 'italic',
    marginTop: 10,
    lineHeight: 20,
  },
  doneLooksUseChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
  },
  doneLooksUseChipText: {
    fontSize: 13,
    fontWeight: '600',
    flexShrink: 1,
  },

  // Compass screens
  compassBeatCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 18,
    gap: 6,
  },
  compassBeatYear: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  compassBeatText: {
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 22,
  },
  compassDominoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    padding: 18,
    gap: 12,
  },
  compassDominoNum: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  compassDominoLabel: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
  },
  compassDominoCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  compassExampleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 20,
  },
  compassExampleLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    flexShrink: 0,
  },
  compassExampleText: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    flex: 1,
  },
  compassFilterPreview: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    marginTop: 16,
    gap: 6,
  },
  compassFilterLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  compassFilterText: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 24,
    fontStyle: 'italic',
  },
  finaleGoalTag: {
    alignSelf: 'flex-start' as const,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 6,
  },
  finaleGoalTagText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase' as const,
  },
  compassCinematicEyebrow: {
    fontSize: 11,
    fontWeight: '800' as const,
    letterSpacing: 1.5,
    textTransform: 'uppercase' as const,
  },
  compassCinematicHeadline: {
    fontSize: 42,
    fontWeight: '900' as const,
    lineHeight: 48,
    letterSpacing: -1,
  },
  compassCinematicBody: {
    fontSize: 16,
    fontWeight: '500' as const,
    lineHeight: 24,
  },
  compassCinematicBodyBold: {
    fontWeight: '800' as const,
  },
  compassCinematicQuote: {
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 24,
  },
  compassCinematicQuoteText: {
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 36,
    fontStyle: 'italic',
    letterSpacing: -0.5,
  },
  compassCinematicRuleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 14,
  },
  compassCinematicChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    minWidth: 54,
    alignItems: 'center' as const,
  },
  compassCinematicChipText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#000',
    letterSpacing: 1,
  },
  compassCinematicRuleText: {
    fontSize: 17,
    fontWeight: '600',
  },
  compassCinematicGoldCard: {
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 24,
    gap: 12,
  },
  compassCinematicGoldTag: {
    alignSelf: 'flex-start' as const,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  compassCinematicGoldTagText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#000',
    letterSpacing: 1.5,
  },
  compassCinematicWinTitle: {
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 36,
  },
  compassCinematicWinSub: {
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 22,
  },
  compassCinematicCloserBold: {
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 28,
    letterSpacing: -0.5,
  },
  welcomeDots: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    alignSelf: 'center' as const,
  },
  welcomeDot: {
    height: 8,
    borderRadius: 4,
  },
  compassPinnedOuter: {
    flex: 1,
    paddingHorizontal: 24,
  },
  compassPinnedTop: {
    paddingTop: 8,
    paddingBottom: 4,
  },
  compassPinnedContent: {
    flex: 1,
    justifyContent: 'flex-start' as const,
    paddingTop: 24,
  },
  compassPinnedBottom: {
    paddingBottom: 20,
  },
});

export default styles;
